#!/bin/csh


set TestDirectory = '/array/hdd/msmajdi/Tests/Thalamus_CNN'
set priorfolderName = 'Manual_Delineation_Sanitized'
# Label ('1-THALAMUS' '8-Pul' '4567-VL') # '2-AV' '4-VA' '5-VLa' '6-VLP' '7-VPL' '9-LGN' '10-MGN' '11-CM' '12-MD-Pf' '13-Hb' 
# set Label = '4567-VL' # '1-THALAMUS' # '8-Pul' # 
# set FolderTest = 'CNN4567_VL_2D_SanitizedNN' # 'CNN1_THALAMUS_2D_SanitizedNN' # 'CNN8_Pul_2D_SanitizedNN' 

# Results	Results2  Results_MultByManualThalamus	

foreach FolderTest ('CNN8_Pul_2D_SanitizedNN' 'CNN12_MD_Pf_2D_SanitizedNN' 'CNN6_VLP_2D_SanitizedNN' 'CNN4567_VL_2D_SanitizedNN' 'CNN1_THALAMUS_2D_SanitizedNN' )
# set reslt = 'Results'

set reusltDirectory = $TestDirectory/Results
mkdir $reusltDirectory
mkdir $reusltDirectory/$FolderTest
echo $FolderTest

cd $TestDirectory/$FolderTest
foreach Test (Test_*)
echo $Test

#set Test = 'Test_WMnMPRAGE_bias_corr_Sharpness_4_Contrast_3_Deformed'
# set Test = 'Test_WMnMPRAGE_bias_corr_Deformed'
mkdir $reusltDirectory/$FolderTest/$Test

cd $Test
foreach vimp (vimp2_*)

	mkdir $reusltDirectory/$FolderTest/$Test/$vimp
	mkdir $reusltDirectory/$FolderTest/$Test/$vimp/Test
        mkdir $reusltDirectory/$FolderTest/$Test/$vimp/Train

	foreach reslt ( 'Results' ) #'Results2' 'Results_MultByManualThalamus' )
	set Directory = $TestDirectory/$FolderTest/$Test/$vimp/Test/$reslt
	# mkdir $Directory
	cp -r $Directory $reusltDirectory/$FolderTest/$Test/$vimp/Test/
	end

        set Directory = $TestDirectory/$FolderTest/$Test/$vimp/Train/model
        cp -r $Directory $reusltDirectory/$FolderTest/$Test/$vimp/Train/

end
cd ../
end
end
