#!/bin/csh


set Test_Dir = '/array/hdd/msmajdi/Tests/Thalamus_CNN'
set Prior_Dir = '/array/hdd/msmajdi/data/priors_forCNN_Ver2/Manual_Delineation_Sanitized_Full'
set Test = 'Test_WMnMPRAGE_bias_corr_Deformed'

foreach FolderTest ('CNN1_THALAMUS_2D_SanitizedNN'  'CNN4567_VL_2D_SanitizedNN' 'CNN6_VLP_2D_SanitizedNN' 'CNN8_Pul_2D_SanitizedNN'  'CNN10_MGN_2D_SanitizedNN' 'CNN12_MD_Pf_2D_SanitizedNN')


foreach vimp ('vimp2_668_02282013_CD' 'vimp2_845_05312013_VZ' 'vimp2_964_08092013_TG' 'vimp2_ANON724_03272013')
	
	set save_Dir = $Test_Dir/Results_Temp/$FolderTest/$Test/$vimp/
	mkdir -p $save_Dir

	set Pred_Dir = $Test_Dir/$FolderTest/$Test/$vimp/Test/Results/
	mkdir $save_Dir/prediction/

	cp $Pred_Dir/DiceCoefficient.txt $save_Dir/prediction/
	cp $Pred_Dir/vimp2_*_Logical.nii.gz $save_Dir/prediction/

	mkdir $save_Dir/original/
	cp -r $Prior_Dir/$vimp/Manual_Delineation_Sanitized $save_Dir/original/
	cp $Prior_Dir/$vimp/WMnMPRAGE_bias_corr_Deformed.nii.gz $save_Dir/original/

end
end

